version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "testguiadodesdecmd"
#s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-upt09go84tay"
s3_prefix = "testguiadodesdecmd"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []
resolve_s3 = true

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "todo-list-aws-staging"
#s3_bucket = "aws-sam-cli-managed-staging-samclisourcebucket-upt09go84tay"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []
